### ISSUE TITLE
MHS Adaptor - handle Unsolicited Message scenarios

### ISSUE THREAD

**Issue by robert-joscelyne** [nhsconnect/integration-adaptors#166]
MHS Adaptor fails when RefToMessageId does not exist (GP2GP and Unsolicited Messages)

**Comment by tomzo** [comment]
When MHS adaptor receives a message that it did not expect, the `RefToMessageId` field is missing in the SOAP header. That's expected because it is the first message in the conversation.

Currently MHS is crashing when it receives a message like that. There is some code that was supposed to handle it, but it was submitted very late and never tested. The code never executes. 

https://github.com/nhsconnect/integration-adaptors/blob/f33deb25e07d4953a641837cf5db8c69bde9ade2/mhs/common/mhs_common/workflow/asynchronous_forward_reliable.py#L85

**Comment by bartek-sarul** [comment]
@tomzo I understand that the expected behaviour is to accept such message and just put on the queue?

**Comment by tomzo** [comment]
> @tomzo I understand that the expected behaviour is to accept such message and just put on the queue?

Yes, that's correct.

**Comment by bartek-sarul** [comment]
https://gpitbjss.atlassian.net/browse/NIAD-133
